# Generated by Django 2.1.4 on 2019-01-01 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HDServer_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('brand', models.CharField(blank=True, max_length=128, null=True)),
                ('brand_type', models.CharField(blank=True, max_length=128, null=True)),
                ('run_env', models.CharField(blank=True, max_length=128, null=True)),
                ('manager_ip', models.CharField(blank=True, max_length=128, null=True)),
                ('device_ip', models.CharField(blank=True, max_length=128, null=True)),
                ('description', models.CharField(blank=True, max_length=128, null=True)),
                ('oper_member', models.CharField(blank=True, max_length=128, null=True)),
                ('department', models.CharField(blank=True, max_length=128, null=True)),
                ('team', models.CharField(blank=True, max_length=128, null=True)),
                ('use_member', models.CharField(blank=True, max_length=128, null=True)),
                ('position', models.CharField(blank=True, max_length=128, null=True)),
                ('datacenter', models.CharField(blank=True, max_length=128, null=True)),
                ('cabinet', models.CharField(blank=True, max_length=128, null=True)),
                ('u_num', models.CharField(blank=True, max_length=128, null=True)),
                ('u_start', models.CharField(blank=True, max_length=128, null=True)),
                ('u_end', models.CharField(blank=True, max_length=128, null=True)),
                ('asset_num', models.CharField(blank=True, max_length=128, null=True)),
                ('asset_sn', models.CharField(blank=True, max_length=128, null=True)),
                ('support_start', models.CharField(blank=True, max_length=128, null=True)),
                ('support_end', models.CharField(blank=True, max_length=128, null=True)),
                ('hd_cost', models.CharField(blank=True, max_length=128, null=True)),
                ('supplier', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
    ]
