# Generated by Django 2.1.4 on 2019-01-01 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hdServer', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HDServer_Data',
            new_name='Data',
        ),
    ]
