# Generated by Django 2.1.4 on 2019-01-05 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hdServer', '0003_cert'),
    ]

    operations = [
        migrations.AddField(
            model_name='cert',
            name='hd_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
