# Generated by Django 2.1.4 on 2019-01-05 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hdServer', '0004_cert_hd_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpmiData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cert_ip', models.CharField(blank=True, max_length=128, null=True)),
                ('brand', models.CharField(blank=True, max_length=128, null=True)),
                ('product_name', models.CharField(blank=True, max_length=128, null=True)),
                ('uuid', models.CharField(blank=True, max_length=128, null=True)),
                ('fw', models.CharField(blank=True, max_length=128, null=True)),
                ('way', models.CharField(blank=True, max_length=128, null=True)),
                ('ip', models.CharField(blank=True, max_length=128, null=True)),
                ('mac', models.CharField(blank=True, max_length=128, null=True)),
                ('sn', models.CharField(blank=True, max_length=128, null=True)),
                ('update_time', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
    ]
