# Generated by Django 2.1.4 on 2019-01-05 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hdServer', '0005_ipmidata'),
    ]

    operations = [
        migrations.AddField(
            model_name='cert',
            name='sync',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
