# Generated by Django 2.1.4 on 2019-01-12 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hdServer', '0007_ilodata'),
    ]

    operations = [
        migrations.AddField(
            model_name='ilodata',
            name='license',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
