# Generated by Django 2.1.4 on 2019-01-12 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hdServer', '0008_ilodata_license'),
    ]

    operations = [
        migrations.AddField(
            model_name='ilodata',
            name='cpu',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ilodata',
            name='disk',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ilodata',
            name='log',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ilodata',
            name='memory',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ilodata',
            name='raid',
            field=models.TextField(blank=True, null=True),
        ),
    ]
