# Generated by Django 2.1.4 on 2019-01-12 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hdServer', '0009_auto_20190112_1755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ilodata',
            name='brand',
        ),
    ]
