# Generated by Django 2.1.4 on 2018-12-19 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setData', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brandtype',
            name='brand_id',
        ),
        migrations.AlterField(
            model_name='brandtype',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='setData.Brand'),
        ),
    ]
