# Generated by Django 2.1.4 on 2018-12-19 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setData', '0003_auto_20181219_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandtype',
            name='brand_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='brandtype',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='setData.Brand'),
        ),
    ]
