# Generated by Django 2.1.4 on 2018-12-19 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setData', '0004_auto_20181219_2256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brandtype',
            name='brand',
        ),
        migrations.DeleteModel(
            name='BrandType',
        ),
    ]
