# Generated by Django 2.1.4 on 2018-12-19 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setData', '0005_auto_20181219_2257'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('brand_name', models.CharField(blank=True, max_length=128, null=True)),
                ('create_time', models.CharField(blank=True, max_length=128, null=True)),
                ('user_create', models.CharField(blank=True, max_length=128, null=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='setData.Brand')),
            ],
        ),
    ]
