# Generated by Django 2.1.4 on 2018-12-19 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setData', '0006_brandtype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='user_create',
            new_name='who_create',
        ),
        migrations.RenameField(
            model_name='brandtype',
            old_name='user_create',
            new_name='who_create',
        ),
    ]
