# Generated by Django 2.1.4 on 2018-12-24 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setData', '0007_auto_20181219_2259'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('Position', models.CharField(max_length=128)),
                ('city', models.CharField(blank=True, max_length=128, null=True)),
                ('address', models.CharField(blank=True, max_length=128, null=True)),
                ('type', models.CharField(blank=True, max_length=128, null=True)),
                ('supplier', models.CharField(blank=True, max_length=128, null=True)),
                ('supplier_phone', models.CharField(blank=True, max_length=128, null=True)),
                ('manager', models.CharField(blank=True, max_length=128, null=True)),
                ('manager_phone', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('city', models.CharField(blank=True, max_length=128, null=True)),
                ('address', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
    ]
