# Generated by Django 2.1.4 on 2018-12-25 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setData', '0008_datacenter_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datacenter',
            old_name='Position',
            new_name='position',
        ),
    ]
