# Generated by Django 2.1.4 on 2018-12-25 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setData', '0009_auto_20181225_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='datacenter',
            name='position_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='datacenter',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='setData.Position'),
        ),
    ]
