# Generated by Django 2.1.5 on 2019-02-24 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('description', models.CharField(blank=True, max_length=128, null=True)),
                ('script_name', models.CharField(blank=True, max_length=32, null=True)),
                ('create_time', models.CharField(blank=True, max_length=128, null=True)),
                ('user', models.CharField(blank=True, max_length=32, null=True)),
            ],
        ),
    ]
