# Generated by Django 2.1.5 on 2019-01-28 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operSystem', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='hdserver',
            new_name='hdserver_id',
        ),
        migrations.AddField(
            model_name='data',
            name='hdserver_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
