# Generated by Django 2.1.5 on 2019-01-29 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operSystem', '0002_auto_20190128_1519'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cert_ip', models.CharField(blank=True, max_length=128, null=True)),
                ('host_ip', models.CharField(blank=True, max_length=128, null=True)),
                ('hostname', models.CharField(blank=True, max_length=128, null=True)),
                ('os_sys', models.CharField(blank=True, max_length=128, null=True)),
                ('os_version', models.CharField(blank=True, max_length=128, null=True)),
                ('os_kernel', models.CharField(blank=True, max_length=128, null=True)),
                ('cpu_model', models.TextField(blank=True, null=True)),
                ('cpu_num', models.CharField(blank=True, max_length=128, null=True)),
                ('cpu_core', models.CharField(blank=True, max_length=128, null=True)),
                ('mem_total', models.CharField(blank=True, max_length=128, null=True)),
                ('disk_total', models.CharField(blank=True, max_length=128, null=True)),
                ('product_id', models.CharField(blank=True, max_length=128, null=True)),
                ('phydisk', models.CharField(blank=True, max_length=128, null=True)),
                ('logicdisk', models.CharField(blank=True, max_length=128, null=True)),
                ('install_date', models.CharField(blank=True, max_length=128, null=True)),
                ('network', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
