# Generated by Django 2.1.5 on 2019-01-29 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operSystem', '0005_syncdata_update_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='cert',
            name='port',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
