# Generated by Django 2.1.5 on 2019-01-29 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operSystem', '0006_cert_port'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syncdata',
            name='logicdisk',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='syncdata',
            name='phydisk',
            field=models.TextField(blank=True, null=True),
        ),
    ]
