# Generated by Django 2.1.5 on 2019-02-16 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operSystem', '0007_auto_20190129_1744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='syncdata',
            name='update_time',
        ),
        migrations.AddField(
            model_name='syncdata',
            name='netstat_foreign',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='syncdata',
            name='netstat_foreign_port',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='syncdata',
            name='netstat_local',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='syncdata',
            name='netstat_local_port',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='syncdata',
            name='netstat_pid',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='syncdata',
            name='netstat_state',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
