# Generated by Django 2.1.5 on 2019-02-16 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operSystem', '0008_auto_20190216_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='syncdata',
            name='update_time',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
