# Generated by Django 2.1.5 on 2019-02-16 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operSystem', '0009_syncdata_update_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='syncdata',
            name='netstat_foreign',
        ),
        migrations.RemoveField(
            model_name='syncdata',
            name='netstat_foreign_port',
        ),
        migrations.RemoveField(
            model_name='syncdata',
            name='netstat_local',
        ),
        migrations.RemoveField(
            model_name='syncdata',
            name='netstat_local_port',
        ),
        migrations.RemoveField(
            model_name='syncdata',
            name='netstat_pid',
        ),
        migrations.RemoveField(
            model_name='syncdata',
            name='netstat_state',
        ),
        migrations.AddField(
            model_name='syncdata',
            name='netstat',
            field=models.TextField(blank=True, null=True),
        ),
    ]
